### ISSUE TITLE
polish allauthors

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/lab#102]
- [x] Sort the output of `.. allauthors::` by contrubutions
 - [x] When there is [no author](https://github.com/Uberspace/lab/blob/67-authorship/authorship/authorship/__init__.py#L39) set the author to Uberspace
 - [x] When there is a URL for the author instead of a email address (`Uberspace <uberspace.de>`), link to that URL ([Uberspace](uberspace.de)).
