### ISSUE TITLE
[meta] add missing programming language tags to guides

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1612]
Some guides do not have any programming language tags like:

```.. tag:: lang-nodejs```

please add the tag(s) accordingly to the used programming languages in the tool. The folloing guides are missing the tags:

- [ ] source/guide_couchdb.rst
- [ ] source/guide_ejabberd.rst
- [ ] source/guide_eturnal.rst
- [ ] source/guide_focalboard.rst
- [ ] source/guide_gancio.rst
- [ ] source/guide_gotosocial.rst
- [ ] source/guide_influxdb2.rst
- [ ] source/guide_jellyfin.rst
- [ ] source/guide_keycloak.rst
- [ ] source/guide_libreoffice.rst
- [ ] source/guide_navidrome.rst
- [ ] source/guide_offen.rst
- [ ] source/guide_prosody.rst
- [ ] source/guide_resilio.rst
- [ ] source/guide_salt.rst
- [ ] source/guide_shellinabox.rst
- [ ] source/guide_tarsnap.rst
- [ ] source/guide_teamcity.rst
- [ ] source/guide_teamspeak.rst
- [ ] source/guide_vaultwarden.rst
- [ ] source/guide_wkd.rst
