### ISSUE TITLE
make it easier to link to manual

### ISSUE THREAD

**Issue by luto** [Uberspace/lab#262]
Almost all guides reference manual pages (e.g. MySQL) using the full URL. This is not easy to maintain in the future and adds noise.

```shell
$ grep -r manual.uberspace.de *.rst | wc -l
166
```

- [x] write a plugin, shortcode, something to reference the manual, e.g. `:manual:mysql`
- [x] replace all links by that shortcode
- [x] add a note about this to the style guide

**Comment by FriedrichFroebel** [comment]
There already seems to be an official Sphinx extension to achieve this result: [`extlinks`](http://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html).

Activate the extension:
```python
# Enable the extension.
extensions = [
  'authorship',
  'sphinx.ext.extlinks',
]

# Configure the extension to kick in when the `manual` directive is used.
extlinks = {"manual": ("https://manual.uberspace.de/%s.html", "")}
```

Now linking to the manual is possible using
```rst
* :manual:`Python <lang-python>`
* :manual:`display text <target>`
```
in the RST files.

This may be simplified by using a custom version of the [extension](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/extlinks.py) to avoid having to write the display text besides the target itself (using a hard-coded dictionary or similar approaches).

**Comment by luto** [comment]
considering the current situation, having to repeat the display text is fair, I guess :sweat_smile:

**Comment by luto** [comment]
The `extlinks` extension is now active thanks to @FriedrichFroebel! This means that all  guides can now be refactored into the new link format. Take a look at the Akaunting guide (3e156181af7894818a68e2d7b4989c6c32a76fdf) as an example on how to do this.

PRs refactoring all or even single guides are very welcome!

**Comment by FriedrichFroebel** [comment]
I will have a look at all the guides, replace the links to the manual and create a corresponding PR in the next days.

Additionally the style guide needs to be changed as well - the new PR to add a guide for *bludit* seems to still use the old way of linking for example, as only this issue (and my old PR) are mentioning this at the moment.

**Comment by luto** [comment]
wow, that would be awesome! :tada: 

> the new PR to add a guide for _bludit_

ha, well, the styleguide (and apparently the reviewer, me) isn't updated yet :man_facepalming: :grin:

**Comment by luto** [comment]
All done thanks to awesome @FriedrichFroebel :tada:
